"""Generate the Swift scorer's parity fixture from the real scoring engine.

Each case is a paper, a config and the breakdown `arxiv_digest.explain_score`
returns for them. The Swift `Scorer` must reproduce every breakdown exactly, so
a scoring change in Python fails the Swift tests until the port follows
(ADR 0009). Papers and author names are invented.

    uv run python ios/scripts/make_parity_fixture.py

writes ios/Tests/ArxivDigestCoreTests/ScoringParityFixture.swift.
"""

from __future__ import annotations

import json
import sys
from dataclasses import asdict, replace
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

import arxiv_digest as ad  # noqa: E402

INVENTED_AUTHORS = ["Mira Castellanos", "okafor", "Jonas Albrecht", "Søren Ødegård", "li"]

BASE = ad.Config(named_authors=INVENTED_AUTHORS)

CONFIGS = {
    # Engine defaults, apart from the (real) default author names.
    "defaults": BASE,
    "substring": replace(BASE, word_boundary_matching=False),
    "custom-weights": replace(
        BASE,
        weights=ad.ScoringWeights(
            core_keyword=3, named_author=10, low_priority_penalty=-2,
            long_abstract_bonus=4, long_abstract_threshold=80,
        ),
    ),
    # Parent feed 'cond-mat' matches every cond-mat.* subject; a zero bonus never hits.
    "parent-feed": replace(
        BASE, feed_weights={"cond-mat": 3, "quant-ph": 0, "physics.optics": -1, "CS.LG": 2},
    ),
    "empty-lists": replace(BASE, core_keywords=[], named_authors=[], low_priority_kw=[], feed_weights={}),
    "tricky-terms": replace(
        BASE,
        core_keywords=["mpo", "Floquet", "  anyons ", "", "c++", "bose-hubbard", "chern number", "ünal"],
        named_authors=["Ada Lovelace", "ma", "Castellanos", "Ødegård", " "],
        low_priority_kw=["review", "machine learning", "dé"],
    ),
}

PAPERS = [
    {
        "id": "2609.30001",
        "title": "Anomalous Floquet Anyons in Driven Optical Lattices",
        "authors": "Mira L. Castellanos, Tomas Reinholt, Aiko Senda",
        "subjects": "Quantum Gases (cond-mat.quant-gas); Quantum Physics (quant-ph)",
        "abstract": (
            "We show that periodic driving of an interacting optical lattice stabilises anyons "
            "with a statistical phase set by the Floquet frequency. Tensor network simulations "
            "of a Bose-Hubbard ladder confirm a non-zero Chern number in transport measurements."
        ),
    },
    {
        "id": "2609.30002",
        "title": "Temporal MPO compression for c++ solvers: a review",
        "authors": "Ruth Okafor, Y. Mao, Jonas K. Albrecht",
        "subjects": "Strongly Correlated Electrons (cond-mat.str-el); Machine Learning (cs.LG)",
        "abstract": "We review MPO-based methods. Machine learning helps.",
    },
    {
        "id": "2609.30003",
        "title": "Photonic waveguides",
        "authors": "Søren Ødegård, Wei Li, Ada Example",
        "subjects": "Optics (physics.optics)",
        "abstract": "Short.",
    },
    {
        "id": "2609.30004",
        "title": "Bob Ada and Charlie Lovelace on transport",
        "authors": "Bob Ada, Charlie Lovelace, Elif Ünal",
        "subjects": "Mesoscale and Nanoscale Physics (cond-mat.mes-hall)",
        "abstract": "Dé-coherence in a film device. " * 12,
    },
    {
        "id": "2609.30005",
        "title": "",
        "authors": "",
        "subjects": "",
        "abstract": "",
    },
]


def build() -> list[dict]:
    cases = []
    for cfg_name, cfg in CONFIGS.items():
        for paper in PAPERS:
            b = ad.explain_score(paper, cfg)
            cases.append({
                "name": f"{cfg_name}/{paper['id']}",
                "config": asdict(cfg),
                "paper": paper,
                "expected": {**b, "keywords": [list(t) for t in b["keywords"]],
                             "authors": [list(t) for t in b["authors"]]},
            })
    return cases


def main() -> None:
    data = json.dumps(build(), indent=1, ensure_ascii=True, sort_keys=True)
    out = ROOT / "ios" / "Tests" / "ArxivDigestCoreTests" / "ScoringParityFixture.swift"
    out.write_text(
        "// Generated by ios/scripts/make_parity_fixture.py. Do not edit by hand.\n"
        "// Expected breakdowns come from arxiv_digest.explain_score; papers and names are invented.\n\n"
        "enum ScoringParityFixture {\n"
        '    static let json = #"""\n'
        f"{data}\n"
        '"""#\n'
        "}\n",
        encoding="utf-8",
    )
    print(f"wrote {out} ({len(build())} cases)")


if __name__ == "__main__":
    main()
