// Generated by ios/scripts/make_parity_fixture.py. Do not edit by hand.
// Expected values come from arxiv_digest.Config.from_json / merge_preset; papers and names are invented.

enum ConfigParityFixture {
    static let json = #"""
{
 "hydrate": [
  {
   "expected": {
    "color_author": "#3fb950",
    "color_font_author": true,
    "color_font_keyword": true,
    "color_font_low_priority": false,
    "color_font_subject": false,
    "color_keyword": "#388bfd",
    "color_low_priority": "#f85149",
    "color_subject": "#a371f7",
    "core_keywords": [
     "geometry",
     "geom",
     "quantum geometry",
     "quantum geom",
     "topological",
     "topolog",
     "anyon",
     "1d",
     "Berry curvature",
     "Berry phase",
     "flat band",
     "Chern band",
     "fractional",
     "fractional quantum hall",
     "quantum hall",
     "quantum hall effect",
     "fqhe",
     "fqh",
     "haldane",
     "landau level",
     "ll",
     "scars",
     "many-body localization",
     "mbl",
     "localization",
     "syk",
     "chaos",
     "Sachdev-Ye-Kitaev",
     "fracton",
     "synthetic dimension",
     "synthetic dim",
     "synthetic gauge",
     "synthetic field",
     "synthetic potential",
     "floquet",
     "floquet engineering",
     "one-dimensional",
     "scar",
     "boson",
     "bosonic BdG",
     "Krylov",
     "Thouless",
     "pumping",
     "gauge field",
     "gauge potential",
     "Peierls phases",
     "topological phase transition",
     "topological order",
     "Chern",
     "Hopf",
     "Hofstadter",
     "Harper",
     "Hatsugai",
     "chain",
     "lattice",
     "mps",
     "dmrg",
     "matrix product",
     "tensor",
     "tensor network",
     "purification",
     "tebd",
     "lindblad",
     "dissipative",
     "open quantum",
     "reservoir",
     "reservoir engineering",
     "quantum gas",
     "ladder",
     "bosonic",
     "mott",
     "doublon",
     "holon",
     "hubbard",
     "supersolid",
     "chiral",
     "spin chain",
     "kitaev",
     "ising",
     "heisenberg",
     "frustrat",
     "entanglement",
     "mpo"
    ],
    "default_feeds": [
     "cond-mat.quant-gas",
     "cond-mat.mes-hall",
     "quant-ph",
     "cond-mat"
    ],
    "feed_weights": {
     "cond-mat.mes-hall": 4,
     "cond-mat.quant-gas": 4,
     "quant-ph": 2
    },
    "feeds": {
     "cond-mat": "https://arxiv.org/list/cond-mat/new",
     "cond-mat.mes-hall": "https://arxiv.org/list/cond-mat.mes-hall/new",
     "cond-mat.quant-gas": "https://arxiv.org/list/cond-mat.quant-gas/new",
     "quant-ph": "https://arxiv.org/list/quant-ph/new"
    },
    "highlight_authors": true,
    "highlight_terms_abstract": true,
    "highlight_terms_summary": false,
    "highlight_terms_title": true,
    "include_replacements": false,
    "low_priority_kw": [
     "film",
     "heterostructure",
     "photoemission",
     "device",
     "junction",
     "transport",
     "measurement",
     "spectroscopy",
     "microscopy",
     "epitaxial",
     "mbe",
     "growth",
     "fabrication",
     "stm",
     "arpes",
     "rixs"
    ],
    "named_authors": [
     "Mira Castellanos",
     "okafor",
     "Jonas Albrecht",
     "S\u00f8ren \u00d8deg\u00e5rd",
     "li"
    ],
    "timeframe": "pastweek",
    "top_n": 20,
    "weights": {
     "core_keyword": 6,
     "long_abstract_bonus": 1,
     "long_abstract_threshold": 200,
     "low_priority_penalty": -5,
     "named_author": 6
    },
    "word_boundary_matching": true
   },
   "input": {
    "named_authors": [
     "Mira Castellanos",
     "okafor",
     "Jonas Albrecht",
     "S\u00f8ren \u00d8deg\u00e5rd",
     "li"
    ]
   }
  },
  {
   "expected": {
    "color_author": "#3fb950",
    "color_font_author": true,
    "color_font_keyword": true,
    "color_font_low_priority": false,
    "color_font_subject": false,
    "color_keyword": "#388bfd",
    "color_low_priority": "#f85149",
    "color_subject": "#a371f7",
    "core_keywords": [],
    "default_feeds": [
     "cond-mat.quant-gas",
     "cond-mat.mes-hall",
     "quant-ph",
     "cond-mat"
    ],
    "feed_weights": {
     "cond-mat.mes-hall": 4,
     "cond-mat.quant-gas": 4,
     "quant-ph": 2
    },
    "feeds": {
     "cond-mat": "https://arxiv.org/list/cond-mat/new",
     "cond-mat.mes-hall": "https://arxiv.org/list/cond-mat.mes-hall/new",
     "cond-mat.quant-gas": "https://arxiv.org/list/cond-mat.quant-gas/new",
     "quant-ph": "https://arxiv.org/list/quant-ph/new"
    },
    "highlight_authors": true,
    "highlight_terms_abstract": true,
    "highlight_terms_summary": false,
    "highlight_terms_title": true,
    "include_replacements": false,
    "low_priority_kw": [],
    "named_authors": [],
    "timeframe": "pastweek",
    "top_n": 20,
    "weights": {
     "core_keyword": 6,
     "long_abstract_bonus": 1,
     "long_abstract_threshold": 200,
     "low_priority_penalty": -5,
     "named_author": 6
    },
    "word_boundary_matching": true
   },
   "input": {
    "core_keywords": [],
    "low_priority_kw": [],
    "named_authors": []
   }
  },
  {
   "expected": {
    "color_author": "#3fb950",
    "color_font_author": true,
    "color_font_keyword": true,
    "color_font_low_priority": false,
    "color_font_subject": false,
    "color_keyword": "#388bfd",
    "color_low_priority": "#f85149",
    "color_subject": "#a371f7",
    "core_keywords": [
     "geometry",
     "geom",
     "quantum geometry",
     "quantum geom",
     "topological",
     "topolog",
     "anyon",
     "1d",
     "Berry curvature",
     "Berry phase",
     "flat band",
     "Chern band",
     "fractional",
     "fractional quantum hall",
     "quantum hall",
     "quantum hall effect",
     "fqhe",
     "fqh",
     "haldane",
     "landau level",
     "ll",
     "scars",
     "many-body localization",
     "mbl",
     "localization",
     "syk",
     "chaos",
     "Sachdev-Ye-Kitaev",
     "fracton",
     "synthetic dimension",
     "synthetic dim",
     "synthetic gauge",
     "synthetic field",
     "synthetic potential",
     "floquet",
     "floquet engineering",
     "one-dimensional",
     "scar",
     "boson",
     "bosonic BdG",
     "Krylov",
     "Thouless",
     "pumping",
     "gauge field",
     "gauge potential",
     "Peierls phases",
     "topological phase transition",
     "topological order",
     "Chern",
     "Hopf",
     "Hofstadter",
     "Harper",
     "Hatsugai",
     "chain",
     "lattice",
     "mps",
     "dmrg",
     "matrix product",
     "tensor",
     "tensor network",
     "purification",
     "tebd",
     "lindblad",
     "dissipative",
     "open quantum",
     "reservoir",
     "reservoir engineering",
     "quantum gas",
     "ladder",
     "bosonic",
     "mott",
     "doublon",
     "holon",
     "hubbard",
     "supersolid",
     "chiral",
     "spin chain",
     "kitaev",
     "ising",
     "heisenberg",
     "frustrat",
     "entanglement",
     "mpo"
    ],
    "default_feeds": [
     "quant-ph"
    ],
    "feed_weights": {
     "cond-mat.mes-hall": 4,
     "cond-mat.quant-gas": 4,
     "quant-ph": 2
    },
    "feeds": {
     "cs.LG": "https://arxiv.org/list/cs.LG/new",
     "quant-ph": "https://arxiv.org/list/quant-ph/new"
    },
    "highlight_authors": true,
    "highlight_terms_abstract": true,
    "highlight_terms_summary": false,
    "highlight_terms_title": true,
    "include_replacements": false,
    "low_priority_kw": [
     "film",
     "heterostructure",
     "photoemission",
     "device",
     "junction",
     "transport",
     "measurement",
     "spectroscopy",
     "microscopy",
     "epitaxial",
     "mbe",
     "growth",
     "fabrication",
     "stm",
     "arpes",
     "rixs"
    ],
    "named_authors": [
     "okafor"
    ],
    "timeframe": "pastweek",
    "top_n": 20,
    "weights": {
     "core_keyword": 6,
     "long_abstract_bonus": 1,
     "long_abstract_threshold": 200,
     "low_priority_penalty": -5,
     "named_author": 6
    },
    "word_boundary_matching": true
   },
   "input": {
    "default_feeds": [
     "quant-ph",
     "unknown"
    ],
    "feeds": {
     "cs.LG": "https://arxiv.org/list/cs.LG/new",
     "quant-ph": "https://arxiv.org/list/quant-ph/new"
    },
    "named_authors": [
     "okafor"
    ]
   }
  },
  {
   "expected": {
    "color_author": "#3fb950",
    "color_font_author": true,
    "color_font_keyword": true,
    "color_font_low_priority": false,
    "color_font_subject": false,
    "color_keyword": "#388bfd",
    "color_low_priority": "#f85149",
    "color_subject": "#a371f7",
    "core_keywords": [
     "geometry",
     "geom",
     "quantum geometry",
     "quantum geom",
     "topological",
     "topolog",
     "anyon",
     "1d",
     "Berry curvature",
     "Berry phase",
     "flat band",
     "Chern band",
     "fractional",
     "fractional quantum hall",
     "quantum hall",
     "quantum hall effect",
     "fqhe",
     "fqh",
     "haldane",
     "landau level",
     "ll",
     "scars",
     "many-body localization",
     "mbl",
     "localization",
     "syk",
     "chaos",
     "Sachdev-Ye-Kitaev",
     "fracton",
     "synthetic dimension",
     "synthetic dim",
     "synthetic gauge",
     "synthetic field",
     "synthetic potential",
     "floquet",
     "floquet engineering",
     "one-dimensional",
     "scar",
     "boson",
     "bosonic BdG",
     "Krylov",
     "Thouless",
     "pumping",
     "gauge field",
     "gauge potential",
     "Peierls phases",
     "topological phase transition",
     "topological order",
     "Chern",
     "Hopf",
     "Hofstadter",
     "Harper",
     "Hatsugai",
     "chain",
     "lattice",
     "mps",
     "dmrg",
     "matrix product",
     "tensor",
     "tensor network",
     "purification",
     "tebd",
     "lindblad",
     "dissipative",
     "open quantum",
     "reservoir",
     "reservoir engineering",
     "quantum gas",
     "ladder",
     "bosonic",
     "mott",
     "doublon",
     "holon",
     "hubbard",
     "supersolid",
     "chiral",
     "spin chain",
     "kitaev",
     "ising",
     "heisenberg",
     "frustrat",
     "entanglement",
     "mpo"
    ],
    "default_feeds": [
     "cond-mat.quant-gas",
     "cond-mat.mes-hall",
     "quant-ph",
     "cond-mat"
    ],
    "feed_weights": {
     "cond-mat.mes-hall": 4,
     "cond-mat.quant-gas": 4,
     "quant-ph": 2
    },
    "feeds": {
     "quant-ph": "https://arxiv.org/list/quant-ph/new"
    },
    "highlight_authors": true,
    "highlight_terms_abstract": true,
    "highlight_terms_summary": false,
    "highlight_terms_title": true,
    "include_replacements": false,
    "low_priority_kw": [
     "film",
     "heterostructure",
     "photoemission",
     "device",
     "junction",
     "transport",
     "measurement",
     "spectroscopy",
     "microscopy",
     "epitaxial",
     "mbe",
     "growth",
     "fabrication",
     "stm",
     "arpes",
     "rixs"
    ],
    "named_authors": [
     "okafor"
    ],
    "timeframe": "pastweek",
    "top_n": 20,
    "weights": {
     "core_keyword": 6,
     "long_abstract_bonus": 1,
     "long_abstract_threshold": 200,
     "low_priority_penalty": -5,
     "named_author": 6
    },
    "word_boundary_matching": true
   },
   "input": {
    "default_feeds": [],
    "feeds": {
     "quant-ph": "https://arxiv.org/list/quant-ph/new"
    },
    "named_authors": [
     "okafor"
    ]
   }
  },
  {
   "expected": {
    "color_author": "#3fb950",
    "color_font_author": true,
    "color_font_keyword": true,
    "color_font_low_priority": false,
    "color_font_subject": false,
    "color_keyword": "#388bfd",
    "color_low_priority": "#f85149",
    "color_subject": "#a371f7",
    "core_keywords": [
     "geometry",
     "geom",
     "quantum geometry",
     "quantum geom",
     "topological",
     "topolog",
     "anyon",
     "1d",
     "Berry curvature",
     "Berry phase",
     "flat band",
     "Chern band",
     "fractional",
     "fractional quantum hall",
     "quantum hall",
     "quantum hall effect",
     "fqhe",
     "fqh",
     "haldane",
     "landau level",
     "ll",
     "scars",
     "many-body localization",
     "mbl",
     "localization",
     "syk",
     "chaos",
     "Sachdev-Ye-Kitaev",
     "fracton",
     "synthetic dimension",
     "synthetic dim",
     "synthetic gauge",
     "synthetic field",
     "synthetic potential",
     "floquet",
     "floquet engineering",
     "one-dimensional",
     "scar",
     "boson",
     "bosonic BdG",
     "Krylov",
     "Thouless",
     "pumping",
     "gauge field",
     "gauge potential",
     "Peierls phases",
     "topological phase transition",
     "topological order",
     "Chern",
     "Hopf",
     "Hofstadter",
     "Harper",
     "Hatsugai",
     "chain",
     "lattice",
     "mps",
     "dmrg",
     "matrix product",
     "tensor",
     "tensor network",
     "purification",
     "tebd",
     "lindblad",
     "dissipative",
     "open quantum",
     "reservoir",
     "reservoir engineering",
     "quantum gas",
     "ladder",
     "bosonic",
     "mott",
     "doublon",
     "holon",
     "hubbard",
     "supersolid",
     "chiral",
     "spin chain",
     "kitaev",
     "ising",
     "heisenberg",
     "frustrat",
     "entanglement",
     "mpo"
    ],
    "default_feeds": [
     "cs.LG"
    ],
    "feed_weights": {
     "cond-mat.mes-hall": 4,
     "cond-mat.quant-gas": 9,
     "quant-ph": 2
    },
    "feeds": {
     "cs.LG": "https://arxiv.org/list/cs.LG/new",
     "quant-ph": "https://arxiv.org/list/quant-ph/new"
    },
    "highlight_authors": true,
    "highlight_terms_abstract": true,
    "highlight_terms_summary": false,
    "highlight_terms_title": true,
    "include_replacements": false,
    "low_priority_kw": [
     "film",
     "heterostructure",
     "photoemission",
     "device",
     "junction",
     "transport",
     "measurement",
     "spectroscopy",
     "microscopy",
     "epitaxial",
     "mbe",
     "growth",
     "fabrication",
     "stm",
     "arpes",
     "rixs"
    ],
    "named_authors": [
     "okafor"
    ],
    "timeframe": "pastweek",
    "top_n": 20,
    "weights": {
     "core_keyword": 7,
     "long_abstract_bonus": 1,
     "long_abstract_threshold": 200,
     "low_priority_penalty": -5,
     "named_author": 2
    },
    "word_boundary_matching": true
   },
   "input": {
    "default_feed": "cs.LG",
    "feeds": {
     "cs.LG": "https://arxiv.org/list/cs.LG/new",
     "quant-ph": "https://arxiv.org/list/quant-ph/new"
    },
    "named_authors": [
     "okafor"
    ],
    "weights": {
     "core_keyword": "7",
     "named_author": 2.0,
     "quant_gas_subject": 9
    }
   }
  },
  {
   "expected": {
    "color_author": "#3fb950",
    "color_font_author": true,
    "color_font_keyword": true,
    "color_font_low_priority": false,
    "color_font_subject": false,
    "color_keyword": "#000000",
    "color_low_priority": "#f85149",
    "color_subject": "#a371f7",
    "core_keywords": [
     "geometry",
     "geom",
     "quantum geometry",
     "quantum geom",
     "topological",
     "topolog",
     "anyon",
     "1d",
     "Berry curvature",
     "Berry phase",
     "flat band",
     "Chern band",
     "fractional",
     "fractional quantum hall",
     "quantum hall",
     "quantum hall effect",
     "fqhe",
     "fqh",
     "haldane",
     "landau level",
     "ll",
     "scars",
     "many-body localization",
     "mbl",
     "localization",
     "syk",
     "chaos",
     "Sachdev-Ye-Kitaev",
     "fracton",
     "synthetic dimension",
     "synthetic dim",
     "synthetic gauge",
     "synthetic field",
     "synthetic potential",
     "floquet",
     "floquet engineering",
     "one-dimensional",
     "scar",
     "boson",
     "bosonic BdG",
     "Krylov",
     "Thouless",
     "pumping",
     "gauge field",
     "gauge potential",
     "Peierls phases",
     "topological phase transition",
     "topological order",
     "Chern",
     "Hopf",
     "Hofstadter",
     "Harper",
     "Hatsugai",
     "chain",
     "lattice",
     "mps",
     "dmrg",
     "matrix product",
     "tensor",
     "tensor network",
     "purification",
     "tebd",
     "lindblad",
     "dissipative",
     "open quantum",
     "reservoir",
     "reservoir engineering",
     "quantum gas",
     "ladder",
     "bosonic",
     "mott",
     "doublon",
     "holon",
     "hubbard",
     "supersolid",
     "chiral",
     "spin chain",
     "kitaev",
     "ising",
     "heisenberg",
     "frustrat",
     "entanglement",
     "mpo"
    ],
    "default_feeds": [
     "cond-mat.quant-gas",
     "cond-mat.mes-hall",
     "quant-ph",
     "cond-mat"
    ],
    "feed_weights": {
     "cond-mat": 3,
     "quant-ph": 2
    },
    "feeds": {
     "cond-mat": "https://arxiv.org/list/cond-mat/new",
     "cond-mat.mes-hall": "https://arxiv.org/list/cond-mat.mes-hall/new",
     "cond-mat.quant-gas": "https://arxiv.org/list/cond-mat.quant-gas/new",
     "quant-ph": "https://arxiv.org/list/quant-ph/new"
    },
    "highlight_authors": false,
    "highlight_terms_abstract": true,
    "highlight_terms_summary": false,
    "highlight_terms_title": true,
    "include_replacements": true,
    "low_priority_kw": [
     "film",
     "heterostructure",
     "photoemission",
     "device",
     "junction",
     "transport",
     "measurement",
     "spectroscopy",
     "microscopy",
     "epitaxial",
     "mbe",
     "growth",
     "fabrication",
     "stm",
     "arpes",
     "rixs"
    ],
    "named_authors": [
     "okafor"
    ],
    "timeframe": "pastweek",
    "top_n": 20,
    "weights": {
     "core_keyword": 6,
     "long_abstract_bonus": 1,
     "long_abstract_threshold": 200,
     "low_priority_penalty": -5,
     "named_author": 6
    },
    "word_boundary_matching": false
   },
   "input": {
    "color_keyword": "#000000",
    "feed_weights": {
     "cond-mat": "3",
     "quant-ph": 2.0
    },
    "highlight_authors": null,
    "include_replacements": "false",
    "named_authors": [
     "okafor"
    ],
    "timeframe": "",
    "top_n": 0,
    "unknown_key": 1,
    "weights": {},
    "word_boundary_matching": 0
   }
  },
  {
   "expected": {
    "color_author": "#3fb950",
    "color_font_author": true,
    "color_font_keyword": true,
    "color_font_low_priority": false,
    "color_font_subject": false,
    "color_keyword": "#388bfd",
    "color_low_priority": "#f85149",
    "color_subject": "#a371f7",
    "core_keywords": [
     "Floquet",
     "5",
     "True"
    ],
    "default_feeds": [
     "cond-mat.quant-gas",
     "cond-mat.mes-hall",
     "quant-ph",
     "cond-mat"
    ],
    "feed_weights": {
     "cond-mat.mes-hall": 4,
     "cond-mat.quant-gas": 4,
     "quant-ph": 2
    },
    "feeds": {
     "cond-mat": "https://arxiv.org/list/cond-mat/new",
     "cond-mat.mes-hall": "https://arxiv.org/list/cond-mat.mes-hall/new",
     "cond-mat.quant-gas": "https://arxiv.org/list/cond-mat.quant-gas/new",
     "quant-ph": "https://arxiv.org/list/quant-ph/new"
    },
    "highlight_authors": true,
    "highlight_terms_abstract": true,
    "highlight_terms_summary": false,
    "highlight_terms_title": true,
    "include_replacements": false,
    "low_priority_kw": [
     "film",
     "heterostructure",
     "photoemission",
     "device",
     "junction",
     "transport",
     "measurement",
     "spectroscopy",
     "microscopy",
     "epitaxial",
     "mbe",
     "growth",
     "fabrication",
     "stm",
     "arpes",
     "rixs"
    ],
    "named_authors": [
     "okafor"
    ],
    "timeframe": "pastweek",
    "top_n": 7,
    "weights": {
     "core_keyword": 6,
     "long_abstract_bonus": 1,
     "long_abstract_threshold": 200,
     "low_priority_penalty": -5,
     "named_author": 6
    },
    "word_boundary_matching": true
   },
   "input": {
    "core_keywords": [
     "Floquet",
     5,
     true
    ],
    "named_authors": [
     "okafor"
    ],
    "top_n": "7"
   }
  }
 ],
 "invalid": [
  {
   "top_n": "abc"
  },
  {
   "feeds": [
    "quant-ph"
   ]
  },
  {
   "weights": {
    "core_keyword": null
   }
  }
 ],
 "merge": [
  {
   "base": {
    "color_author": "#3fb950",
    "color_font_author": true,
    "color_font_keyword": true,
    "color_font_low_priority": false,
    "color_font_subject": false,
    "color_keyword": "#388bfd",
    "color_low_priority": "#f85149",
    "color_subject": "#a371f7",
    "core_keywords": [
     "Lindblad",
     "anyons"
    ],
    "default_feeds": [
     "cond-mat.quant-gas",
     "cond-mat.mes-hall",
     "quant-ph",
     "cond-mat"
    ],
    "feed_weights": {
     "quant-ph": 9
    },
    "feeds": {
     "cond-mat": "https://arxiv.org/list/cond-mat/new",
     "cond-mat.mes-hall": "https://arxiv.org/list/cond-mat.mes-hall/new",
     "cond-mat.quant-gas": "https://arxiv.org/list/cond-mat.quant-gas/new",
     "quant-ph": "https://arxiv.org/list/quant-ph/new"
    },
    "highlight_authors": true,
    "highlight_terms_abstract": true,
    "highlight_terms_summary": false,
    "highlight_terms_title": true,
    "include_replacements": false,
    "low_priority_kw": [
     "film",
     "heterostructure",
     "photoemission",
     "device",
     "junction",
     "transport",
     "measurement",
     "spectroscopy",
     "microscopy",
     "epitaxial",
     "mbe",
     "growth",
     "fabrication",
     "stm",
     "arpes",
     "rixs"
    ],
    "named_authors": [
     "okafor"
    ],
    "timeframe": "pastweek",
    "top_n": 20,
    "weights": {
     "core_keyword": 6,
     "long_abstract_bonus": 1,
     "long_abstract_threshold": 200,
     "low_priority_penalty": -5,
     "named_author": 6
    },
    "word_boundary_matching": true
   },
   "expected": {
    "color_author": "#3fb950",
    "color_font_author": true,
    "color_font_keyword": true,
    "color_font_low_priority": false,
    "color_font_subject": false,
    "color_keyword": "#388bfd",
    "color_low_priority": "#f85149",
    "color_subject": "#a371f7",
    "core_keywords": [
     "Lindblad",
     "anyons",
     "lindbladian",
     "open quantum system",
     "master equation",
     "dissipative",
     "dissipation",
     "driven-dissipative",
     "non-markovian",
     "decoherence",
     "quantum trajectory",
     "steady state",
     "bath engineering",
     "quantum reservoir",
     "dephasing"
    ],
    "default_feeds": [
     "cond-mat.quant-gas",
     "cond-mat.mes-hall",
     "quant-ph",
     "cond-mat",
     "cond-mat.stat-mech"
    ],
    "feed_weights": {
     "cond-mat.quant-gas": 2,
     "cond-mat.stat-mech": 3,
     "quant-ph": 3
    },
    "feeds": {
     "cond-mat": "https://arxiv.org/list/cond-mat/new",
     "cond-mat.mes-hall": "https://arxiv.org/list/cond-mat.mes-hall/new",
     "cond-mat.quant-gas": "https://arxiv.org/list/cond-mat.quant-gas/new",
     "cond-mat.stat-mech": "https://arxiv.org/list/cond-mat.stat-mech/new",
     "quant-ph": "https://arxiv.org/list/quant-ph/new"
    },
    "highlight_authors": true,
    "highlight_terms_abstract": true,
    "highlight_terms_summary": false,
    "highlight_terms_title": true,
    "include_replacements": false,
    "low_priority_kw": [
     "film",
     "heterostructure",
     "photoemission",
     "device",
     "junction",
     "transport",
     "measurement",
     "spectroscopy",
     "microscopy",
     "epitaxial",
     "mbe",
     "growth",
     "fabrication",
     "stm",
     "arpes",
     "rixs"
    ],
    "named_authors": [
     "okafor",
     "schnell",
     "zoller",
     "cirac",
     "plenio",
     "breuer",
     "diehl"
    ],
    "timeframe": "pastweek",
    "top_n": 20,
    "weights": {
     "core_keyword": 6,
     "long_abstract_bonus": 1,
     "long_abstract_threshold": 200,
     "low_priority_penalty": -5,
     "named_author": 6
    },
    "word_boundary_matching": true
   },
   "preset": "open-quantum-systems"
  },
  {
   "base": {
    "color_author": "#3fb950",
    "color_font_author": true,
    "color_font_keyword": true,
    "color_font_low_priority": false,
    "color_font_subject": false,
    "color_keyword": "#388bfd",
    "color_low_priority": "#f85149",
    "color_subject": "#a371f7",
    "core_keywords": [
     "Lindblad",
     "anyons"
    ],
    "default_feeds": [
     "cond-mat.quant-gas",
     "cond-mat.mes-hall",
     "quant-ph",
     "cond-mat"
    ],
    "feed_weights": {
     "quant-ph": 9
    },
    "feeds": {
     "cond-mat": "https://arxiv.org/list/cond-mat/new",
     "cond-mat.mes-hall": "https://arxiv.org/list/cond-mat.mes-hall/new",
     "cond-mat.quant-gas": "https://arxiv.org/list/cond-mat.quant-gas/new",
     "quant-ph": "https://arxiv.org/list/quant-ph/new"
    },
    "highlight_authors": true,
    "highlight_terms_abstract": true,
    "highlight_terms_summary": false,
    "highlight_terms_title": true,
    "include_replacements": false,
    "low_priority_kw": [
     "film",
     "heterostructure",
     "photoemission",
     "device",
     "junction",
     "transport",
     "measurement",
     "spectroscopy",
     "microscopy",
     "epitaxial",
     "mbe",
     "growth",
     "fabrication",
     "stm",
     "arpes",
     "rixs"
    ],
    "named_authors": [
     "okafor"
    ],
    "timeframe": "pastweek",
    "top_n": 20,
    "weights": {
     "core_keyword": 6,
     "long_abstract_bonus": 1,
     "long_abstract_threshold": 200,
     "low_priority_penalty": -5,
     "named_author": 6
    },
    "word_boundary_matching": true
   },
   "expected": {
    "color_author": "#3fb950",
    "color_font_author": true,
    "color_font_keyword": true,
    "color_font_low_priority": false,
    "color_font_subject": false,
    "color_keyword": "#388bfd",
    "color_low_priority": "#f85149",
    "color_subject": "#a371f7",
    "core_keywords": [
     "Lindblad",
     "anyons",
     "many-body localization",
     "thermalization",
     "prethermal",
     "eigenstate thermalization",
     "entanglement entropy",
     "tensor network",
     "matrix product state",
     "dmrg",
     "quench dynamics",
     "hubbard model",
     "spin chain",
     "strongly correlated",
     "quantum quench",
     "ergodicity"
    ],
    "default_feeds": [
     "cond-mat.quant-gas",
     "cond-mat.mes-hall",
     "quant-ph",
     "cond-mat",
     "cond-mat.str-el",
     "cond-mat.stat-mech"
    ],
    "feed_weights": {
     "cond-mat.quant-gas": 3,
     "cond-mat.stat-mech": 2,
     "cond-mat.str-el": 4,
     "quant-ph": 2
    },
    "feeds": {
     "cond-mat": "https://arxiv.org/list/cond-mat/new",
     "cond-mat.mes-hall": "https://arxiv.org/list/cond-mat.mes-hall/new",
     "cond-mat.quant-gas": "https://arxiv.org/list/cond-mat.quant-gas/new",
     "cond-mat.stat-mech": "https://arxiv.org/list/cond-mat.stat-mech/new",
     "cond-mat.str-el": "https://arxiv.org/list/cond-mat.str-el/new",
     "quant-ph": "https://arxiv.org/list/quant-ph/new"
    },
    "highlight_authors": true,
    "highlight_terms_abstract": true,
    "highlight_terms_summary": false,
    "highlight_terms_title": true,
    "include_replacements": false,
    "low_priority_kw": [
     "film",
     "heterostructure",
     "photoemission",
     "device",
     "junction",
     "transport",
     "measurement",
     "spectroscopy",
     "microscopy",
     "epitaxial",
     "mbe",
     "growth",
     "fabrication",
     "stm",
     "arpes",
     "rixs"
    ],
    "named_authors": [
     "okafor",
     "eisert",
     "cirac",
     "abanin",
     "huse",
     "altman",
     "bloch"
    ],
    "timeframe": "pastweek",
    "top_n": 20,
    "weights": {
     "core_keyword": 6,
     "long_abstract_bonus": 1,
     "long_abstract_threshold": 200,
     "low_priority_penalty": -5,
     "named_author": 6
    },
    "word_boundary_matching": true
   },
   "preset": "quantum-many-body"
  },
  {
   "base": {
    "color_author": "#3fb950",
    "color_font_author": true,
    "color_font_keyword": true,
    "color_font_low_priority": false,
    "color_font_subject": false,
    "color_keyword": "#388bfd",
    "color_low_priority": "#f85149",
    "color_subject": "#a371f7",
    "core_keywords": [
     "Lindblad",
     "anyons"
    ],
    "default_feeds": [
     "cond-mat.quant-gas",
     "cond-mat.mes-hall",
     "quant-ph",
     "cond-mat"
    ],
    "feed_weights": {
     "quant-ph": 9
    },
    "feeds": {
     "cond-mat": "https://arxiv.org/list/cond-mat/new",
     "cond-mat.mes-hall": "https://arxiv.org/list/cond-mat.mes-hall/new",
     "cond-mat.quant-gas": "https://arxiv.org/list/cond-mat.quant-gas/new",
     "quant-ph": "https://arxiv.org/list/quant-ph/new"
    },
    "highlight_authors": true,
    "highlight_terms_abstract": true,
    "highlight_terms_summary": false,
    "highlight_terms_title": true,
    "include_replacements": false,
    "low_priority_kw": [
     "film",
     "heterostructure",
     "photoemission",
     "device",
     "junction",
     "transport",
     "measurement",
     "spectroscopy",
     "microscopy",
     "epitaxial",
     "mbe",
     "growth",
     "fabrication",
     "stm",
     "arpes",
     "rixs"
    ],
    "named_authors": [
     "okafor"
    ],
    "timeframe": "pastweek",
    "top_n": 20,
    "weights": {
     "core_keyword": 6,
     "long_abstract_bonus": 1,
     "long_abstract_threshold": 200,
     "low_priority_penalty": -5,
     "named_author": 6
    },
    "word_boundary_matching": true
   },
   "expected": {
    "color_author": "#3fb950",
    "color_font_author": true,
    "color_font_keyword": true,
    "color_font_low_priority": false,
    "color_font_subject": false,
    "color_keyword": "#388bfd",
    "color_low_priority": "#f85149",
    "color_subject": "#a371f7",
    "core_keywords": [
     "Lindblad",
     "anyons",
     "floquet",
     "periodically driven",
     "topological insulator",
     "chern number",
     "fractional chern",
     "anomalous floquet",
     "berry curvature",
     "optical lattice",
     "ultracold atoms",
     "shortcuts to adiabaticity",
     "lattice gauge",
     "bose-einstein condensate",
     "topological invariant"
    ],
    "default_feeds": [
     "cond-mat.quant-gas",
     "cond-mat.mes-hall",
     "quant-ph",
     "cond-mat"
    ],
    "feed_weights": {
     "cond-mat.mes-hall": 4,
     "cond-mat.quant-gas": 4,
     "quant-ph": 2
    },
    "feeds": {
     "cond-mat": "https://arxiv.org/list/cond-mat/new",
     "cond-mat.mes-hall": "https://arxiv.org/list/cond-mat.mes-hall/new",
     "cond-mat.quant-gas": "https://arxiv.org/list/cond-mat.quant-gas/new",
     "quant-ph": "https://arxiv.org/list/quant-ph/new"
    },
    "highlight_authors": true,
    "highlight_terms_abstract": true,
    "highlight_terms_summary": false,
    "highlight_terms_title": true,
    "include_replacements": false,
    "low_priority_kw": [
     "film",
     "heterostructure",
     "photoemission",
     "device",
     "junction",
     "transport",
     "measurement",
     "spectroscopy",
     "microscopy",
     "epitaxial",
     "mbe",
     "growth",
     "fabrication",
     "stm",
     "arpes",
     "rixs"
    ],
    "named_authors": [
     "okafor",
     "cooper",
     "goldman",
     "aidelsburger",
     "bloch",
     "refael",
     "lindner",
     "rudner"
    ],
    "timeframe": "pastweek",
    "top_n": 20,
    "weights": {
     "core_keyword": 6,
     "long_abstract_bonus": 1,
     "long_abstract_threshold": 200,
     "low_priority_penalty": -5,
     "named_author": 6
    },
    "word_boundary_matching": true
   },
   "preset": "floquet-topological"
  }
 ]
}
"""#
}
