import Foundation

/// The engine's config rules for Standalone mode: `Config()` defaults, the
/// starter presets, `Config.from_json` (the server's `_hydrate`) and
/// `merge_preset`. Pinned by `EngineConfigParityTests`.
public enum EngineConfig {
    struct Generated: Decodable {
        let defaults: [String: JSONValue]
        let presets: [String: DigestRouter.Preset]
    }

    // Generated by make_parity_fixture.py; a decode failure is a build-time bug.
    static let generated = try! JSONDecoder().decode(Generated.self, from: Data(EngineDefaults.json.utf8))
    public static var defaults: [String: JSONValue] { generated.defaults }
    public static var presets: [String: DigestRouter.Preset] { generated.presets }

    public struct Invalid: Error, CustomStringConvertible {
        public let description: String
    }

    /// `asdict(Config.from_json(data))`: every field present, Python's
    /// coercions (`int()`, `bool()`, `str()`), and a list that is present stays
    /// as is even when empty. Throws where Python raises.
    public static func hydrate(_ data: [String: JSONValue]) throws -> [String: JSONValue] {
        let d = defaults
        var feeds: [String: JSONValue] = [:]
        if let raw = data["feeds"], truthy(raw) {
            guard case .object(let o) = raw else { throw Invalid(description: "feeds must be an object") }
            feeds = o.mapValues { .string(str($0)) }
        }

        var defaultFeeds: [String]
        if case .array(let names) = data["default_feeds"] {
            defaultFeeds = names.map(str).filter { feeds[$0] != nil }
        } else if let legacy = data["default_feed"], truthy(legacy), feeds[str(legacy)] != nil {
            defaultFeeds = [str(legacy)]
        } else {
            // ponytail: Python keeps the JSON's key order here; Swift dicts don't, so sort.
            defaultFeeds = feeds.keys.sorted()
        }
        if defaultFeeds.isEmpty { defaultFeeds = d["default_feeds"]?.arrayValue ?? [] }

        var out = d
        out["feeds"] = feeds.isEmpty ? d["feeds"] : .object(feeds)
        out["default_feeds"] = .array(defaultFeeds.map { .string($0) })
        for key in ["core_keywords", "named_authors", "low_priority_kw"] {
            if case .array(let items) = data[key] { out[key] = .array(items.map { .string(str($0)) }) }
        }
        out["top_n"] = .int(try data["top_n"].flatMap { truthy($0) ? try int($0) : nil } ?? 20)
        out["timeframe"] = .string(data["timeframe"].flatMap { truthy($0) ? str($0) : nil } ?? "pastweek")
        for (key, value) in d {
            guard let given = data[key] else { continue }
            switch value {
            case .bool: out[key] = .bool(truthy(given))
            case .string where key.hasPrefix("color_"): out[key] = .string(str(given))
            default: break
            }
        }
        out["feed_weights"] = .object(try feedWeights(data).mapValues { .int($0) })
        out["weights"] = .object(try weights(data["weights"]).mapValues { .int($0) })
        return out
    }

    /// `_hydrate_feed_weights`, including the legacy `weights.*_subject` migration.
    private static func feedWeights(_ data: [String: JSONValue]) throws -> [String: Int] {
        if case .object(let o) = data["feed_weights"] { return try o.mapValues(int) }
        var fw = (defaults["feed_weights"]?.objectValue ?? [:]).compactMapValues(\.intValue)
        let w = data["weights"]?.objectValue ?? [:]
        for (old, feed) in [("quant_gas_subject", "cond-mat.quant-gas"), ("mes_hall_subject", "cond-mat.mes-hall"),
                            ("quant_ph_subject", "quant-ph")] {
            if let v = w[old] { fw[feed] = try int(v) }
        }
        return fw
    }

    /// `ScoringWeights.from_json`.
    private static func weights(_ raw: JSONValue?) throws -> [String: Int] {
        let d = (defaults["weights"]?.objectValue ?? [:]).compactMapValues(\.intValue)
        guard case .object(let o)? = raw, !o.isEmpty else { return d }
        var out: [String: Int] = [:]
        for (key, value) in d { out[key] = try o[key].map(int) ?? value }
        return out
    }

    /// `merge_preset`: keywords, authors and subscribed feeds unioned
    /// (case-insensitive, order kept); feeds and feed weights merged with the
    /// preset winning; everything else kept from `base`.
    public static func merge(_ base: [String: JSONValue], preset: [String: JSONValue]) -> [String: JSONValue] {
        var out = base
        for key in ["core_keywords", "named_authors", "default_feeds"] {
            var list = base[key]?.arrayValue ?? []
            var seen = Set(list.map { $0.lowercased() })
            for item in preset[key]?.arrayValue ?? [] where seen.insert(item.lowercased()).inserted {
                list.append(item)
            }
            out[key] = .array(list.map { .string($0) })
        }
        for key in ["feeds", "feed_weights"] {
            out[key] = .object((base[key]?.objectValue ?? [:]).merging(preset[key]?.objectValue ?? [:]) { _, new in new })
        }
        return out
    }

    // MARK: - Python coercions

    static func truthy(_ v: JSONValue) -> Bool {
        switch v {
        case .null: return false
        case .bool(let b): return b
        case .int(let i): return i != 0
        case .double(let x): return x != 0
        case .string(let s): return !s.isEmpty
        case .array(let a): return !a.isEmpty
        case .object(let o): return !o.isEmpty
        }
    }

    /// Python's `str()` for JSON scalars.
    static func str(_ v: JSONValue) -> String {
        switch v {
        case .string(let s): return s
        case .int(let i): return String(i)
        case .double(let x): return String(x)
        case .bool(let b): return b ? "True" : "False"
        case .null: return "None"
        case .array, .object: return "\(v)"
        }
    }

    /// Python's `int()`: truncates floats, parses strings, rejects the rest.
    static func int(_ v: JSONValue) throws -> Int {
        switch v {
        case .int(let i): return i
        case .double(let x) where x.isFinite: return Int(x.rounded(.towardZero))
        case .bool(let b): return b ? 1 : 0
        case .string(let s):
            if let i = Int(s.trimmingCharacters(in: .whitespaces)) { return i }
            throw Invalid(description: "invalid literal for int() with base 10: '\(s)'")
        default:
            throw Invalid(description: "int() argument must be a string or a number, not '\(str(v))'")
        }
    }
}

/// JSON files in one directory (Application Support on the device, a temp
/// directory in tests). Writes are atomic.
public struct LocalStore: Sendable {
    public let directory: URL

    public init(directory: URL) {
        self.directory = directory
    }

    /// `Application Support/Standalone`.
    public static var standard: LocalStore {
        let base = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask).first
            ?? FileManager.default.temporaryDirectory
        return LocalStore(directory: base.appendingPathComponent("Standalone", isDirectory: true))
    }

    public func load<T: Decodable>(_ type: T.Type, from name: String) -> T? {
        guard let data = try? Data(contentsOf: directory.appendingPathComponent(name)) else { return nil }
        return try? JSONDecoder().decode(T.self, from: data)
    }

    public func save<T: Encodable>(_ value: T, to name: String) {
        // ponytail: a failed write only loses persistence, never the in-memory state.
        try? FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        try? JSONEncoder().encode(value).write(to: directory.appendingPathComponent(name), options: .atomic)
    }
}
