// Generated by ios/scripts/make_demo_fixture.py. Do not edit by hand.
// Scores/breakdowns come from arxiv_digest.explain_score; papers and names are invented.

enum DemoFixture {
    static let json = #"""
{
 "config": {
  "color_author": "#3fb950",
  "color_font_author": true,
  "color_font_keyword": true,
  "color_font_low_priority": false,
  "color_font_subject": false,
  "color_keyword": "#388bfd",
  "color_low_priority": "#f85149",
  "color_subject": "#a371f7",
  "core_keywords": [
   "floquet",
   "topological",
   "anyons",
   "chern number",
   "lindblad",
   "open quantum system",
   "tensor network",
   "optical lattice",
   "many-body localization",
   "bose-hubbard"
  ],
  "default_feeds": [
   "cond-mat.quant-gas",
   "cond-mat.mes-hall",
   "quant-ph"
  ],
  "feed_weights": {
   "cond-mat.mes-hall": 4,
   "cond-mat.quant-gas": 4,
   "quant-ph": 2
  },
  "feeds": {
   "cond-mat.mes-hall": "https://arxiv.org/list/cond-mat.mes-hall/new",
   "cond-mat.quant-gas": "https://arxiv.org/list/cond-mat.quant-gas/new",
   "cond-mat.str-el": "https://arxiv.org/list/cond-mat.str-el/new",
   "quant-ph": "https://arxiv.org/list/quant-ph/new"
  },
  "highlight_authors": true,
  "highlight_terms_abstract": true,
  "highlight_terms_summary": false,
  "highlight_terms_title": true,
  "include_replacements": false,
  "low_priority_kw": [
   "photonic",
   "machine learning",
   "review"
  ],
  "named_authors": [
   "Mira Castellanos",
   "Jonas Albrecht",
   "okafor"
  ],
  "timeframe": "pastweek",
  "top_n": 10,
  "weights": {
   "core_keyword": 6,
   "long_abstract_bonus": 1,
   "long_abstract_threshold": 200,
   "low_priority_penalty": -5,
   "named_author": 6
  },
  "word_boundary_matching": true
 },
 "days": [
  "Mon, 28 Sep 2026",
  "Tue, 29 Sep 2026",
  "Wed, 30 Sep 2026",
  "Thu, 01 Oct 2026",
  "Fri, 02 Oct 2026"
 ],
 "pastweek": [
  {
   "abstract": "We show that periodic driving of an interacting optical lattice stabilises anyons with a statistical phase set by the Floquet frequency. The anomalous Floquet phase hosts chiral edge modes although every Floquet band has zero Chern number. Exact diagonalisation and tensor network simulations of a Bose-Hubbard ladder show that the braiding phase survives heating times well beyond current experiments.",
   "authors": "Mira L. Castellanos, Tomas Reinholt, Aiko Senda",
   "breakdown": {
    "signals": {
     "keyword": {
      "abstract_bonus": 1,
      "authors": [
       [
        "Mira Castellanos",
        6
       ]
      ],
      "keywords": [
       [
        "floquet",
        6
       ],
       [
        "anyons",
        6
       ],
       [
        "chern number",
        6
       ],
       [
        "tensor network",
        6
       ],
       [
        "optical lattice",
        6
       ],
       [
        "bose-hubbard",
        6
       ]
      ],
      "low_priority_hits": [],
      "low_priority_penalty": 0,
      "subjects": {
       "cond-mat.quant-gas": 4,
       "quant-ph": 2
      },
      "total": 49
     }
    },
    "total": 49
   },
   "id": "2609.21407",
   "link": "https://arxiv.org/abs/2609.21407",
   "rank": 0,
   "score": 49,
   "section": "Fri, 02 Oct 2026",
   "subjects": "cond-mat.quant-gas, quant-ph",
   "summary": "We show that periodic driving of an interacting optical lattice stabilises anyons with a statistical phase set by the Floquet frequency. The anomalous Floquet phase hosts chiral edge modes although every Floquet band has zero Chern number.",
   "title": "Anomalous Floquet Anyons in Driven Optical Lattices"
  },
  {
   "abstract": "Engineered dissipation can prepare topological phases as the unique steady state of a Lindblad master equation. We classify which jump operators preserve a non-zero Chern number and derive a gap condition that bounds the preparation time in an open quantum system of fermions on a lattice.",
   "authors": "Jonas Albrecht, Leila Haddad",
   "breakdown": {
    "signals": {
     "keyword": {
      "abstract_bonus": 1,
      "authors": [
       [
        "Jonas Albrecht",
        6
       ]
      ],
      "keywords": [
       [
        "topological",
        6
       ],
       [
        "chern number",
        6
       ],
       [
        "lindblad",
        6
       ],
       [
        "open quantum system",
        6
       ]
      ],
      "low_priority_hits": [],
      "low_priority_penalty": 0,
      "subjects": {
       "cond-mat.mes-hall": 4,
       "quant-ph": 2
      },
      "total": 37
     }
    },
    "total": 37
   },
   "id": "2609.21188",
   "link": "https://arxiv.org/abs/2609.21188",
   "rank": 0,
   "score": 37,
   "section": "Thu, 01 Oct 2026",
   "subjects": "quant-ph, cond-mat.mes-hall",
   "summary": "Engineered dissipation can prepare topological phases as the unique steady state of a Lindblad master equation. We classify which jump operators preserve a non-zero Chern number and derive a gap condition that bounds the preparation time in an open quantum system of fermions on a lattice.",
   "title": "Lindblad Engineering of Topological Steady States"
  },
  {
   "abstract": "We propose a protocol that reads out the Chern number of an optical lattice band from the time-of-flight images after a sudden quench. The method needs no adiabatic loading and is robust to a finite temperature and to weak interactions.",
   "authors": "Ruth Okafor, Daniel Meyrink, Sana Qureshi",
   "breakdown": {
    "signals": {
     "keyword": {
      "abstract_bonus": 1,
      "authors": [
       [
        "okafor",
        6
       ]
      ],
      "keywords": [
       [
        "chern number",
        6
       ],
       [
        "optical lattice",
        6
       ]
      ],
      "low_priority_hits": [],
      "low_priority_penalty": 0,
      "subjects": {
       "cond-mat.quant-gas": 4
      },
      "total": 23
     }
    },
    "total": 23
   },
   "id": "2609.20954",
   "link": "https://arxiv.org/abs/2609.20954",
   "rank": 0,
   "score": 23,
   "section": "Wed, 30 Sep 2026",
   "subjects": "cond-mat.quant-gas",
   "summary": "We propose a protocol that reads out the Chern number of an optical lattice band from the time-of-flight images after a sudden quench. The method needs no adiabatic loading and is robust to a finite temperature and to weak interactions.",
   "title": "Chern Number Tomography from Quench Dynamics"
  },
  {
   "abstract": "Using an infinite tensor network ansatz we map the ground-state phase diagram of the two-dimensional Bose-Hubbard model at filling one half with nearest-neighbour repulsion, finding a supersolid region bounded by first-order transitions.",
   "authors": "Pieter van Loon, Hana Kobayashi",
   "breakdown": {
    "signals": {
     "keyword": {
      "abstract_bonus": 1,
      "authors": [],
      "keywords": [
       [
        "tensor network",
        6
       ],
       [
        "bose-hubbard",
        6
       ]
      ],
      "low_priority_hits": [],
      "low_priority_penalty": 0,
      "subjects": {
       "cond-mat.quant-gas": 4
      },
      "total": 17
     }
    },
    "total": 17
   },
   "id": "2609.20711",
   "link": "https://arxiv.org/abs/2609.20711",
   "rank": 0,
   "score": 17,
   "section": "Tue, 29 Sep 2026",
   "subjects": "cond-mat.str-el, cond-mat.quant-gas",
   "summary": "Using an infinite tensor network ansatz we map the ground-state phase diagram of the two-dimensional Bose-Hubbard model at filling one half with nearest-neighbour repulsion, finding a supersolid region bounded by first-order transitions.",
   "title": "Tensor Network Study of the Bose-Hubbard Model at Fractional Filling"
  },
  {
   "abstract": "We study many-body localization in a quasiperiodic spin chain under periodic kicks. The Floquet eigenstates stay area-law entangled up to a critical drive amplitude, beyond which the system heats to infinite temperature.",
   "authors": "Elena Varga, Marco Pellizzari",
   "breakdown": {
    "signals": {
     "keyword": {
      "abstract_bonus": 1,
      "authors": [],
      "keywords": [
       [
        "floquet",
        6
       ],
       [
        "many-body localization",
        6
       ]
      ],
      "low_priority_hits": [],
      "low_priority_penalty": 0,
      "subjects": {
       "quant-ph": 2
      },
      "total": 15
     }
    },
    "total": 15
   },
   "id": "2609.21530",
   "link": "https://arxiv.org/abs/2609.21530",
   "rank": 0,
   "score": 15,
   "section": "Fri, 02 Oct 2026",
   "subjects": "cond-mat.dis-nn, quant-ph",
   "summary": "We study many-body localization in a quasiperiodic spin chain under periodic kicks. The Floquet eigenstates stay area-law entangled up to a critical drive amplitude, beyond which the system heats to infinite temperature.",
   "title": "Many-Body Localization in Quasiperiodic Floquet Chains"
  },
  {
   "abstract": "Twisted bilayers with a moire potential host corner modes protected by crystalline symmetry. We compute the quadrupole moment and show how the corner charge responds to an applied displacement field.",
   "authors": "Chen Wei, Ingrid Solberg, Tomas Reinholt",
   "breakdown": {
    "signals": {
     "keyword": {
      "abstract_bonus": 0,
      "authors": [],
      "keywords": [
       [
        "topological",
        6
       ]
      ],
      "low_priority_hits": [],
      "low_priority_penalty": 0,
      "subjects": {
       "cond-mat.mes-hall": 4
      },
      "total": 10
     }
    },
    "total": 10
   },
   "id": "2609.20333",
   "link": "https://arxiv.org/abs/2609.20333",
   "rank": 0,
   "score": 10,
   "section": "Mon, 28 Sep 2026",
   "subjects": "cond-mat.mes-hall",
   "summary": "Twisted bilayers with a moire potential host corner modes protected by crystalline symmetry. We compute the quadrupole moment and show how the corner charge responds to an applied displacement field.",
   "title": "Edge States of Higher-Order Topological Insulators in Moire Bilayers"
  },
  {
   "abstract": "We review photonic waveguide arrays and coupled resonators as platforms for Floquet topological insulators, summarising experiments on anomalous edge transport and the measurement of winding numbers in synthetic dimensions.",
   "authors": "Amara Diallo",
   "breakdown": {
    "signals": {
     "keyword": {
      "abstract_bonus": 1,
      "authors": [],
      "keywords": [
       [
        "floquet",
        6
       ],
       [
        "topological",
        6
       ]
      ],
      "low_priority_hits": [
       "photonic",
       "review"
      ],
      "low_priority_penalty": -5,
      "subjects": {
       "quant-ph": 2
      },
      "total": 10
     }
    },
    "total": 10
   },
   "id": "2609.20877",
   "link": "https://arxiv.org/abs/2609.20877",
   "rank": 0,
   "score": 10,
   "section": "Wed, 30 Sep 2026",
   "subjects": "physics.optics, quant-ph",
   "summary": "We review photonic waveguide arrays and coupled resonators as platforms for Floquet topological insulators, summarising experiments on anomalous edge transport and the measurement of winding numbers in synthetic dimensions.",
   "title": "Photonic Realization of Floquet Topological Insulators: A Review"
  },
  {
   "abstract": "Rydberg tweezer arrays with engineered decay realise an open quantum system whose steady state is a resonating valence bond liquid. We give the fidelity as a function of array size and decay rate.",
   "authors": "Ruth Okafor, Felix Brandt",
   "breakdown": {
    "signals": {
     "keyword": {
      "abstract_bonus": 0,
      "authors": [
       [
        "okafor",
        6
       ]
      ],
      "keywords": [
       [
        "open quantum system",
        6
       ]
      ],
      "low_priority_hits": [],
      "low_priority_penalty": 0,
      "subjects": {
       "quant-ph": 2
      },
      "total": 14
     }
    },
    "total": 14
   },
   "id": "2609.21002",
   "link": "https://arxiv.org/abs/2609.21002",
   "rank": 0,
   "score": 14,
   "section": "Thu, 01 Oct 2026",
   "subjects": "quant-ph, cond-mat.str-el",
   "summary": "Rydberg tweezer arrays with engineered decay realise an open quantum system whose steady state is a resonating valence bond liquid. We give the fidelity as a function of array size and decay rate.",
   "title": "Dissipative Preparation of Spin Liquids with Rydberg Arrays"
  },
  {
   "abstract": "A convolutional network trained on snapshots of a driven Bose gas in an optical lattice locates the superfluid to Mott transition within two percent of quantum Monte Carlo.",
   "authors": "Kenji Arakawa, Lucia Romero",
   "breakdown": {
    "signals": {
     "keyword": {
      "abstract_bonus": 0,
      "authors": [],
      "keywords": [
       [
        "optical lattice",
        6
       ]
      ],
      "low_priority_hits": [
       "machine learning"
      ],
      "low_priority_penalty": -5,
      "subjects": {
       "cond-mat.quant-gas": 4
      },
      "total": 5
     }
    },
    "total": 5
   },
   "id": "2609.20519",
   "link": "https://arxiv.org/abs/2609.20519",
   "rank": 0,
   "score": 5,
   "section": "Tue, 29 Sep 2026",
   "subjects": "cond-mat.quant-gas, cs.LG",
   "summary": "A convolutional network trained on snapshots of a driven Bose gas in an optical lattice locates the superfluid to Mott transition within two percent of quantum Monte Carlo.",
   "title": "Machine Learning Phase Boundaries of Driven Bose Gases"
  },
  {
   "abstract": "We compute the thermal Hall conductivity of a Kitaev magnet in a tilted field with a self-consistent spin-wave theory and compare with recent measurements.",
   "authors": "Ingrid Solberg, Rafael Mendes",
   "breakdown": {
    "signals": {
     "keyword": {
      "abstract_bonus": 0,
      "authors": [],
      "keywords": [],
      "low_priority_hits": [],
      "low_priority_penalty": 0,
      "subjects": {},
      "total": 0
     }
    },
    "total": 0
   },
   "id": "2609.20166",
   "link": "https://arxiv.org/abs/2609.20166",
   "rank": 0,
   "score": 0,
   "section": "Mon, 28 Sep 2026",
   "subjects": "cond-mat.str-el",
   "summary": "We compute the thermal Hall conductivity of a Kitaev magnet in a tilted field with a self-consistent spin-wave theory and compare with recent measurements.",
   "title": "Thermal Transport in Kitaev Magnets"
  },
  {
   "abstract": "We propose a Fabry-Perot interferometer that distinguishes non-Abelian anyons in a quantum Hall bilayer by the parity of the enclosed quasiparticle number.",
   "authors": "Sana Qureshi, Jonas Albrecht, Leon Hartmann",
   "breakdown": {
    "signals": {
     "keyword": {
      "abstract_bonus": 0,
      "authors": [
       [
        "Jonas Albrecht",
        6
       ]
      ],
      "keywords": [
       [
        "anyons",
        6
       ]
      ],
      "low_priority_hits": [],
      "low_priority_penalty": 0,
      "subjects": {
       "cond-mat.mes-hall": 4
      },
      "total": 16
     }
    },
    "total": 16
   },
   "id": "2609.21455",
   "link": "https://arxiv.org/abs/2609.21455",
   "rank": 0,
   "score": 16,
   "section": "Fri, 02 Oct 2026",
   "subjects": "cond-mat.mes-hall",
   "summary": "We propose a Fabry-Perot interferometer that distinguishes non-Abelian anyons in a quantum Hall bilayer by the parity of the enclosed quasiparticle number.",
   "title": "Interferometric Detection of Non-Abelian Anyons in Quantum Hall Bilayers"
  },
  {
   "abstract": "We benchmark zero-noise extrapolation and probabilistic error cancellation for variational eigensolvers on twelve superconducting qubits.",
   "authors": "Grace Whitfield, Omar Saleh",
   "breakdown": {
    "signals": {
     "keyword": {
      "abstract_bonus": 0,
      "authors": [],
      "keywords": [],
      "low_priority_hits": [],
      "low_priority_penalty": 0,
      "subjects": {
       "quant-ph": 2
      },
      "total": 2
     }
    },
    "total": 2
   },
   "id": "2609.20640",
   "link": "https://arxiv.org/abs/2609.20640",
   "rank": 0,
   "score": 2,
   "section": "Tue, 29 Sep 2026",
   "subjects": "quant-ph",
   "summary": "We benchmark zero-noise extrapolation and probabilistic error cancellation for variational eigensolvers on twelve superconducting qubits.",
   "title": "Quantum Error Mitigation for Variational Eigensolvers"
  },
  {
   "abstract": "Collective coupling to an optical cavity generates spin squeezing of ten decibels in an ensemble of strontium atoms.",
   "authors": "Helena Novak",
   "breakdown": {
    "signals": {
     "keyword": {
      "abstract_bonus": 0,
      "authors": [],
      "keywords": [],
      "low_priority_hits": [],
      "low_priority_penalty": 0,
      "subjects": {
       "quant-ph": 2
      },
      "total": 2
     }
    },
    "total": 2
   },
   "id": "2609.20288",
   "link": "https://arxiv.org/abs/2609.20288",
   "rank": 0,
   "score": 2,
   "section": "Mon, 28 Sep 2026",
   "subjects": "quant-ph, physics.atom-ph",
   "summary": "Collective coupling to an optical cavity generates spin squeezing of ten decibels in an ensemble of strontium atoms.",
   "title": "Spin Squeezing in Cavity-Coupled Atomic Ensembles"
  },
  {
   "abstract": "We report a nonreciprocal critical current in twisted trilayer graphene and relate it to valley polarisation.",
   "authors": "Marco Pellizzari, Chen Wei",
   "breakdown": {
    "signals": {
     "keyword": {
      "abstract_bonus": 0,
      "authors": [],
      "keywords": [],
      "low_priority_hits": [],
      "low_priority_penalty": 0,
      "subjects": {
       "cond-mat.mes-hall": 4
      },
      "total": 4
     }
    },
    "total": 4
   },
   "id": "2609.20999",
   "link": "https://arxiv.org/abs/2609.20999",
   "rank": 0,
   "score": 4,
   "section": "Wed, 30 Sep 2026",
   "subjects": "cond-mat.supr-con, cond-mat.mes-hall",
   "summary": "We report a nonreciprocal critical current in twisted trilayer graphene and relate it to valley polarisation.",
   "title": "Superconducting Diode Effect in Twisted Trilayer Graphene"
  }
 ],
 "presets": {
  "floquet-topological": {
   "config": {
    "color_author": "#3fb950",
    "color_font_author": true,
    "color_font_keyword": true,
    "color_font_low_priority": false,
    "color_font_subject": false,
    "color_keyword": "#388bfd",
    "color_low_priority": "#f85149",
    "color_subject": "#a371f7",
    "core_keywords": [
     "floquet",
     "periodically driven",
     "topological insulator",
     "chern number",
     "fractional chern",
     "anomalous floquet",
     "berry curvature",
     "optical lattice",
     "ultracold atoms",
     "shortcuts to adiabaticity",
     "anyons",
     "lattice gauge",
     "bose-einstein condensate",
     "topological invariant"
    ],
    "default_feeds": [
     "cond-mat.quant-gas",
     "cond-mat.mes-hall",
     "quant-ph"
    ],
    "feed_weights": {
     "cond-mat.mes-hall": 4,
     "cond-mat.quant-gas": 4,
     "quant-ph": 2
    },
    "feeds": {
     "cond-mat.mes-hall": "https://arxiv.org/list/cond-mat.mes-hall/new",
     "cond-mat.quant-gas": "https://arxiv.org/list/cond-mat.quant-gas/new",
     "quant-ph": "https://arxiv.org/list/quant-ph/new"
    },
    "highlight_authors": true,
    "highlight_terms_abstract": true,
    "highlight_terms_summary": false,
    "highlight_terms_title": true,
    "include_replacements": false,
    "low_priority_kw": [
     "film",
     "heterostructure",
     "photoemission",
     "device",
     "junction",
     "transport",
     "measurement",
     "spectroscopy",
     "microscopy",
     "epitaxial",
     "mbe",
     "growth",
     "fabrication",
     "stm",
     "arpes",
     "rixs"
    ],
    "named_authors": [
     "cooper",
     "goldman",
     "aidelsburger",
     "bloch",
     "refael",
     "lindner",
     "rudner"
    ],
    "timeframe": "pastweek",
    "top_n": 20,
    "weights": {
     "core_keyword": 6,
     "long_abstract_bonus": 1,
     "long_abstract_threshold": 200,
     "low_priority_penalty": -5,
     "named_author": 6
    },
    "word_boundary_matching": true
   },
   "description": "Floquet engineering, periodically driven systems & topological matter (group signature)."
  },
  "open-quantum-systems": {
   "config": {
    "color_author": "#3fb950",
    "color_font_author": true,
    "color_font_keyword": true,
    "color_font_low_priority": false,
    "color_font_subject": false,
    "color_keyword": "#388bfd",
    "color_low_priority": "#f85149",
    "color_subject": "#a371f7",
    "core_keywords": [
     "lindblad",
     "lindbladian",
     "open quantum system",
     "master equation",
     "dissipative",
     "dissipation",
     "driven-dissipative",
     "non-markovian",
     "decoherence",
     "quantum trajectory",
     "steady state",
     "bath engineering",
     "quantum reservoir",
     "dephasing"
    ],
    "default_feeds": [
     "quant-ph",
     "cond-mat.stat-mech",
     "cond-mat.quant-gas"
    ],
    "feed_weights": {
     "cond-mat.quant-gas": 2,
     "cond-mat.stat-mech": 3,
     "quant-ph": 3
    },
    "feeds": {
     "cond-mat.quant-gas": "https://arxiv.org/list/cond-mat.quant-gas/new",
     "cond-mat.stat-mech": "https://arxiv.org/list/cond-mat.stat-mech/new",
     "quant-ph": "https://arxiv.org/list/quant-ph/new"
    },
    "highlight_authors": true,
    "highlight_terms_abstract": true,
    "highlight_terms_summary": false,
    "highlight_terms_title": true,
    "include_replacements": false,
    "low_priority_kw": [
     "film",
     "heterostructure",
     "photoemission",
     "device",
     "junction",
     "transport",
     "measurement",
     "spectroscopy",
     "microscopy",
     "epitaxial",
     "mbe",
     "growth",
     "fabrication",
     "stm",
     "arpes",
     "rixs"
    ],
    "named_authors": [
     "schnell",
     "zoller",
     "cirac",
     "plenio",
     "breuer",
     "diehl"
    ],
    "timeframe": "pastweek",
    "top_n": 20,
    "weights": {
     "core_keyword": 6,
     "long_abstract_bonus": 1,
     "long_abstract_threshold": 200,
     "low_priority_penalty": -5,
     "named_author": 6
    },
    "word_boundary_matching": true
   },
   "description": "Lindbladian dynamics, dissipation, driven-dissipative & non-Markovian systems."
  },
  "quantum-many-body": {
   "config": {
    "color_author": "#3fb950",
    "color_font_author": true,
    "color_font_keyword": true,
    "color_font_low_priority": false,
    "color_font_subject": false,
    "color_keyword": "#388bfd",
    "color_low_priority": "#f85149",
    "color_subject": "#a371f7",
    "core_keywords": [
     "many-body localization",
     "thermalization",
     "prethermal",
     "eigenstate thermalization",
     "entanglement entropy",
     "tensor network",
     "matrix product state",
     "dmrg",
     "quench dynamics",
     "hubbard model",
     "spin chain",
     "strongly correlated",
     "quantum quench",
     "ergodicity"
    ],
    "default_feeds": [
     "cond-mat.str-el",
     "cond-mat.quant-gas",
     "cond-mat.stat-mech",
     "quant-ph"
    ],
    "feed_weights": {
     "cond-mat.quant-gas": 3,
     "cond-mat.stat-mech": 2,
     "cond-mat.str-el": 4,
     "quant-ph": 2
    },
    "feeds": {
     "cond-mat.quant-gas": "https://arxiv.org/list/cond-mat.quant-gas/new",
     "cond-mat.stat-mech": "https://arxiv.org/list/cond-mat.stat-mech/new",
     "cond-mat.str-el": "https://arxiv.org/list/cond-mat.str-el/new",
     "quant-ph": "https://arxiv.org/list/quant-ph/new"
    },
    "highlight_authors": true,
    "highlight_terms_abstract": true,
    "highlight_terms_summary": false,
    "highlight_terms_title": true,
    "include_replacements": false,
    "low_priority_kw": [
     "film",
     "heterostructure",
     "photoemission",
     "device",
     "junction",
     "transport",
     "measurement",
     "spectroscopy",
     "microscopy",
     "epitaxial",
     "mbe",
     "growth",
     "fabrication",
     "stm",
     "arpes",
     "rixs"
    ],
    "named_authors": [
     "eisert",
     "cirac",
     "abanin",
     "huse",
     "altman",
     "bloch"
    ],
    "timeframe": "pastweek",
    "top_n": 20,
    "weights": {
     "core_keyword": 6,
     "long_abstract_bonus": 1,
     "long_abstract_threshold": 200,
     "low_priority_penalty": -5,
     "named_author": 6
    },
    "word_boundary_matching": true
   },
   "description": "Thermalization, many-body localization, tensor networks & strongly correlated systems."
  }
 },
 "today": [
  {
   "abstract": "We show that periodic driving of an interacting optical lattice stabilises anyons with a statistical phase set by the Floquet frequency. The anomalous Floquet phase hosts chiral edge modes although every Floquet band has zero Chern number. Exact diagonalisation and tensor network simulations of a Bose-Hubbard ladder show that the braiding phase survives heating times well beyond current experiments.",
   "authors": "Mira L. Castellanos, Tomas Reinholt, Aiko Senda",
   "breakdown": {
    "signals": {
     "keyword": {
      "abstract_bonus": 1,
      "authors": [
       [
        "Mira Castellanos",
        6
       ]
      ],
      "keywords": [
       [
        "floquet",
        6
       ],
       [
        "anyons",
        6
       ],
       [
        "chern number",
        6
       ],
       [
        "tensor network",
        6
       ],
       [
        "optical lattice",
        6
       ],
       [
        "bose-hubbard",
        6
       ]
      ],
      "low_priority_hits": [],
      "low_priority_penalty": 0,
      "subjects": {
       "cond-mat.quant-gas": 4,
       "quant-ph": 2
      },
      "total": 49
     }
    },
    "total": 49
   },
   "id": "2609.21407",
   "link": "https://arxiv.org/abs/2609.21407",
   "rank": 0,
   "score": 49,
   "section": "New submissions (showing 1 of 1 entries)",
   "subjects": "cond-mat.quant-gas, quant-ph",
   "summary": "We show that periodic driving of an interacting optical lattice stabilises anyons with a statistical phase set by the Floquet frequency. The anomalous Floquet phase hosts chiral edge modes although every Floquet band has zero Chern number.",
   "title": "Anomalous Floquet Anyons in Driven Optical Lattices"
  },
  {
   "abstract": "We study many-body localization in a quasiperiodic spin chain under periodic kicks. The Floquet eigenstates stay area-law entangled up to a critical drive amplitude, beyond which the system heats to infinite temperature.",
   "authors": "Elena Varga, Marco Pellizzari",
   "breakdown": {
    "signals": {
     "keyword": {
      "abstract_bonus": 1,
      "authors": [],
      "keywords": [
       [
        "floquet",
        6
       ],
       [
        "many-body localization",
        6
       ]
      ],
      "low_priority_hits": [],
      "low_priority_penalty": 0,
      "subjects": {
       "quant-ph": 2
      },
      "total": 15
     }
    },
    "total": 15
   },
   "id": "2609.21530",
   "link": "https://arxiv.org/abs/2609.21530",
   "rank": 0,
   "score": 15,
   "section": "Cross submissions (showing 1 of 1 entries)",
   "subjects": "cond-mat.dis-nn, quant-ph",
   "summary": "We study many-body localization in a quasiperiodic spin chain under periodic kicks. The Floquet eigenstates stay area-law entangled up to a critical drive amplitude, beyond which the system heats to infinite temperature.",
   "title": "Many-Body Localization in Quasiperiodic Floquet Chains"
  },
  {
   "abstract": "We propose a Fabry-Perot interferometer that distinguishes non-Abelian anyons in a quantum Hall bilayer by the parity of the enclosed quasiparticle number.",
   "authors": "Sana Qureshi, Jonas Albrecht, Leon Hartmann",
   "breakdown": {
    "signals": {
     "keyword": {
      "abstract_bonus": 0,
      "authors": [
       [
        "Jonas Albrecht",
        6
       ]
      ],
      "keywords": [
       [
        "anyons",
        6
       ]
      ],
      "low_priority_hits": [],
      "low_priority_penalty": 0,
      "subjects": {
       "cond-mat.mes-hall": 4
      },
      "total": 16
     }
    },
    "total": 16
   },
   "id": "2609.21455",
   "link": "https://arxiv.org/abs/2609.21455",
   "rank": 0,
   "score": 16,
   "section": "New submissions (showing 1 of 1 entries)",
   "subjects": "cond-mat.mes-hall",
   "summary": "We propose a Fabry-Perot interferometer that distinguishes non-Abelian anyons in a quantum Hall bilayer by the parity of the enclosed quasiparticle number.",
   "title": "Interferometric Detection of Non-Abelian Anyons in Quantum Hall Bilayers"
  },
  {
   "abstract": "Engineered dissipation can prepare topological phases as the unique steady state of a Lindblad master equation. We classify which jump operators preserve a non-zero Chern number and derive a gap condition that bounds the preparation time in an open quantum system of fermions on a lattice.",
   "authors": "Jonas Albrecht, Leila Haddad",
   "breakdown": {
    "signals": {
     "keyword": {
      "abstract_bonus": 1,
      "authors": [
       [
        "Jonas Albrecht",
        6
       ]
      ],
      "keywords": [
       [
        "topological",
        6
       ],
       [
        "chern number",
        6
       ],
       [
        "lindblad",
        6
       ],
       [
        "open quantum system",
        6
       ]
      ],
      "low_priority_hits": [],
      "low_priority_penalty": 0,
      "subjects": {
       "cond-mat.mes-hall": 4,
       "quant-ph": 2
      },
      "total": 37
     }
    },
    "total": 37
   },
   "id": "2609.21188",
   "link": "https://arxiv.org/abs/2609.21188",
   "rank": 0,
   "score": 37,
   "section": "Replacement submissions (showing 1 of 1 entries)",
   "subjects": "quant-ph, cond-mat.mes-hall",
   "summary": "Engineered dissipation can prepare topological phases as the unique steady state of a Lindblad master equation. We classify which jump operators preserve a non-zero Chern number and derive a gap condition that bounds the preparation time in an open quantum system of fermions on a lattice.",
   "title": "Lindblad Engineering of Topological Steady States"
  }
 ]
}
"""#
}
